<?php
/**
 * Template Name: Reset Password
 *
 * A04.1 / A03.3 — External user sets a new password via a recovery token.
 * Token is generated by admin-initiated reset (A04) or self-service recovery (A03).
 * Invalid or expired tokens redirect to the password recovery page (expired state).
 *
 * @package ascendum-brand-center
 */

defined( 'ABSPATH' ) || exit;

// Redirect already-authenticated users away.
if ( is_user_logged_in() ) {
    wp_safe_redirect( abc_homepage_url() );
    exit;
}

$recovery_url = home_url( '/password-recovery/' );

// ----- Token validation -----------------------------------------------------
$token = isset( $_GET['token'] ) ? sanitize_text_field( wp_unslash( $_GET['token'] ) ) : '';

if ( empty( $token ) ) {
    wp_safe_redirect( add_query_arg( 'expired', '1', $recovery_url ) );
    exit;
}

$token_hash  = wp_hash( $token );
$token_users = get_users( array(
    'meta_key'   => 'abc_recovery_token',
    'meta_value' => $token_hash,
    'number'     => 1,
    'fields'     => 'ID',
) );

if ( empty( $token_users ) ) {
    wp_safe_redirect( add_query_arg( 'expired', '1', $recovery_url ) );
    exit;
}

$reset_user_id = (int) $token_users[0];
$expires       = (int) get_user_meta( $reset_user_id, 'abc_recovery_expires', true );

if ( time() > $expires ) {
    wp_safe_redirect( add_query_arg( 'expired', '1', $recovery_url ) );
    exit;
}

// ----- Error message map ----------------------------------------------------
$pw_error_messages = array(
    'required' => __( 'Both password fields are required.', 'ascendum-brand-center' ),
    'mismatch' => __( 'Passwords do not match. Please try again.', 'ascendum-brand-center' ),
    'weak'     => __( 'Password does not meet the requirements. Please try again.', 'ascendum-brand-center' ),
    'system'   => __( 'An unexpected error occurred. Please try again shortly.', 'ascendum-brand-center' ),
);

$pw_error_key = isset( $_GET['pw_error'] ) ? sanitize_key( $_GET['pw_error'] ) : '';
$pw_error_msg = isset( $pw_error_messages[ $pw_error_key ] ) ? $pw_error_messages[ $pw_error_key ] : '';

// ----- ACF field values (shared group_login_page) ---------------------------
$bg_image            = get_field( 'login_image' );
$login_title         = get_field( 'login_title' );
$login_introduction  = get_field( 'login_introduction' );
$login_subtitle      = get_field( 'login_subtitle' );
$institutional_label = get_field( 'login_institutional_label' );
$institutional_url   = get_field( 'login_institutional_url' );
$social_links        = abc_get_social_links();
$legal_links         = abc_get_legal_links();
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php wp_head(); ?>
</head>
<body <?php body_class( 'set-password-page-body' ); ?>>
<?php wp_body_open(); ?>

<div class="set-password-page">

    <!-- ── Left column: background image ───────────────────────────────────── -->
    <div class="set-password-image" role="img" aria-hidden="true">
        <?php if ( $bg_image ) : ?>
            <img
                src="<?php echo esc_url( $bg_image['url'] ); ?>"
                alt=""
                width="<?php echo esc_attr( $bg_image['width'] ); ?>"
                height="<?php echo esc_attr( $bg_image['height'] ); ?>"
            >
        <?php endif; ?>
    </div>

    <!-- ── Right column: sidebar ────────────────────────────────────────────── -->
    <aside class="set-password-sidebar" aria-label="<?php esc_attr_e( 'Set new password', 'ascendum-brand-center' ); ?>">

        <!-- Content: headline + form -->
        <div class="set-password-sidebar-content">

            <!-- Headline area (optional) -->
            <?php if ( $login_title || $login_introduction || $login_subtitle ) : ?>
            <div class="set-password-headline">
                <?php if ( $login_title ) : ?>
                    <h1 class="set-password-title"><?php echo esc_html( $login_title ); ?></h1>
                <?php endif; ?>
                <?php if ( $login_introduction ) : ?>
                    <p class="set-password-introduction"><?php echo esc_html( $login_introduction ); ?></p>
                <?php endif; ?>
                <?php if ( $login_subtitle ) : ?>
                    <p class="set-password-subtitle"><?php echo esc_html( $login_subtitle ); ?></p>
                <?php endif; ?>
            </div>
            <?php endif; ?>

            <!-- Reset password form -->
            <form
                class="set-password-form"
                method="post"
                action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"
                novalidate
            >
                <input type="hidden" name="action" value="abc_reset_password">
                <input type="hidden" name="abc_token" value="<?php echo esc_attr( $token ); ?>">
                <?php wp_nonce_field( 'abc_reset_password_' . $token, 'abc_reset_password_nonce' ); ?>

                <div class="set-password-fields">
                    <p class="set-password-form-label">
                        <?php esc_html_e( 'Define your password', 'ascendum-brand-center' ); ?>
                    </p>

                    <?php if ( $pw_error_msg ) : ?>
                    <div class="set-password-error-message" role="alert">
                        <?php echo esc_html( $pw_error_msg ); ?>
                    </div>
                    <?php endif; ?>

                    <div class="set-password-field">
                        <label class="screen-reader-text" for="rp-password">
                            <?php esc_html_e( 'New password', 'ascendum-brand-center' ); ?>
                        </label>
                        <input
                            type="password"
                            id="rp-password"
                            name="password"
                            class="set-password-input<?php echo ( 'required' === $pw_error_key || 'weak' === $pw_error_key ) ? ' is-error' : ''; ?>"
                            placeholder="<?php esc_attr_e( 'Enter new password', 'ascendum-brand-center' ); ?>"
                            autocomplete="new-password"
                        >
                        <p class="set-password-hint">
                            <?php esc_html_e( 'Password must be at least 8 characters long and include an uppercase letter, a number, and a special character.', 'ascendum-brand-center' ); ?>
                        </p>
                    </div>

                    <div class="set-password-field">
                        <label class="screen-reader-text" for="rp-password2">
                            <?php esc_html_e( 'Confirm new password', 'ascendum-brand-center' ); ?>
                        </label>
                        <input
                            type="password"
                            id="rp-password2"
                            name="password2"
                            class="set-password-input<?php echo ( 'required' === $pw_error_key || 'mismatch' === $pw_error_key ) ? ' is-error' : ''; ?>"
                            placeholder="<?php esc_attr_e( 'Confirm new password', 'ascendum-brand-center' ); ?>"
                            autocomplete="new-password"
                        >
                    </div>
                </div>

                <button type="submit" class="set-password-btn">
                    <?php esc_html_e( 'Confirm', 'ascendum-brand-center' ); ?>
                </button>

                <div class="set-password-options">
                    <a href="<?php echo esc_url( abc_login_url() ); ?>" class="set-password-back-link">
                        <?php esc_html_e( 'Back to Login', 'ascendum-brand-center' ); ?>
                    </a>
                </div>

            </form>

        </div><!-- /.set-password-sidebar-content -->

        <!-- Footer separator -->
        <div class="set-password-footer-separator" aria-hidden="true"></div>

        <!-- Footer -->
        <footer class="set-password-footer">

            <div class="set-password-social-row">
                <?php if ( $institutional_label && $institutional_url ) : ?>
                <a
                    href="<?php echo esc_url( $institutional_url ); ?>"
                    class="set-password-institutional-link"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <?php echo esc_html( $institutional_label ); ?>
                </a>
                <?php endif; ?>

                <?php if ( $social_links ) : ?>
                <div class="set-password-social-icons">
                    <?php foreach ( $social_links as $item ) :
                        $icon = $item['social_icon'];
                        $url  = $item['social_url'];
                        if ( ! $icon || ! $url ) {
                            continue;
                        }
                        $alt = ! empty( $icon['alt'] ) ? $icon['alt'] : ( ! empty( $icon['title'] ) ? $icon['title'] : '' );
                    ?>
                    <a
                        href="<?php echo esc_url( $url ); ?>"
                        class="set-password-social-icon-link"
                        target="_blank"
                        rel="noopener noreferrer"
                        <?php if ( $alt ) : ?>aria-label="<?php echo esc_attr( $alt ); ?>"<?php endif; ?>
                    >
                        <img
                            src="<?php echo esc_url( $icon['url'] ); ?>"
                            alt=""
                            width="24"
                            height="24"
                        >
                    </a>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>
            </div>

            <?php if ( $legal_links ) : ?>
            <div class="set-password-legal-links">
                <?php foreach ( $legal_links as $item ) :
                    $label = $item['legal_label'];
                    $url   = $item['legal_url'];
                    if ( ! $label || ! $url ) {
                        continue;
                    }
                ?>
                <a
                    href="<?php echo esc_url( $url ); ?>"
                    class="set-password-legal-link"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <?php echo esc_html( $label ); ?>
                </a>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>

            <p class="set-password-copyright">
                <?php esc_html_e( '@Ascendum 2025 All rights reserved', 'ascendum-brand-center' ); ?>
            </p>

        </footer>

    </aside><!-- /.set-password-sidebar -->

</div><!-- /.set-password-page -->

<?php wp_footer(); ?>
</body>
</html>
